backend:
  name: git-gateway
  repo: ribeiroevandro/mmenu
  branch: main
  local_backend: true

media_folder: public/static/img
public_folder: /static/img

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - name: 'pages'
    label: 'Páginas'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Produtos'
    name: 'products'
    folder: 'src/content/products'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Nome', name: 'title', widget: 'string', required: true }
      - {
          label: 'Preço',
          name: 'price',
          widget: 'number',
          value_type: 'int',
          required: true
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Imagens',
          name: 'thumbnail',
          widget: 'image',
          required: true,
          allow_multiple: true
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
