backend:
  name: git-gateway
  repo: ribeiroevandro/mmenu
  branch: main
  local_backend: true

media_folder: public/static/img
public_folder: /static/img

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'

collections:
  - name: 'pages'
    label: 'Páginas'
    show_preview_links: true
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Produtos'
    name: 'products'
    folder: 'src/content/products'
    create: true
    slug: '{{slug}}'
    preview_path: '{{slug}}'
    fields:
      - { label: 'Nome', name: 'title', widget: 'string', required: true }
      - {
          label: 'Preço',
          name: 'price',
          widget: 'number',
          value_type: 'int',
          required: true
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - {
          label: 'Imagem Destaque',
          name: 'thumbnail_featured',
          widget: 'image',
          required: true,
        }
      - {
          label: 'Galeria',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.thumbnail_featured}}',
          field: {
            label: 'Imagem',
            name: 'thumbnail',
            widget: 'image'
          }
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: "Mostrar em destaque?", name: "home_page", widget: "boolean", default: false}
